--------------------------------------------------------
--  파일이 생성됨 - 수요일-4월-30-2025   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Sequence SEQL
--------------------------------------------------------

   CREATE SEQUENCE  "JUXXI"."SEQL"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 5 START WITH 10 NOCACHE  NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
--------------------------------------------------------
--  DDL for Sequence SEQSHOP
--------------------------------------------------------

   CREATE SEQUENCE  "JUXXI"."SEQSHOP"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 2 START WITH 13 NOCACHE  NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
--------------------------------------------------------
--  DDL for Sequence SEQ_BOARD
--------------------------------------------------------

   CREATE SEQUENCE  "JUXXI"."SEQ_BOARD"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 41 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
--------------------------------------------------------
--  DDL for Sequence SEQ_FOOD
--------------------------------------------------------

   CREATE SEQUENCE  "JUXXI"."SEQ_FOOD"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 3 START WITH 52 NOCACHE  NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
--------------------------------------------------------
--  DDL for Sequence SEQ_SAWON
--------------------------------------------------------

   CREATE SEQUENCE  "JUXXI"."SEQ_SAWON"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 16 NOCACHE  NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
--------------------------------------------------------
--  DDL for Sequence SEQ_SHOP
--------------------------------------------------------

   CREATE SEQUENCE  "JUXXI"."SEQ_SHOP"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 21 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
--------------------------------------------------------
--  DDL for Sequence SEQ_TEST
--------------------------------------------------------

   CREATE SEQUENCE  "JUXXI"."SEQ_TEST"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 41 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
--------------------------------------------------------
--  DDL for Table ANSWER
--------------------------------------------------------

  CREATE TABLE "JUXXI"."ANSWER" 
   (	"NUM" NUMBER(5,0), 
	"BNO" NUMBER(3,0), 
	"NICKNAME" VARCHAR2(30 BYTE), 
	"CONTENT" VARCHAR2(100 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table BOARD
--------------------------------------------------------

  CREATE TABLE "JUXXI"."BOARD" 
   (	"BNO" NUMBER(3,0), 
	"WRITER" VARCHAR2(30 BYTE), 
	"SUBJECT" VARCHAR2(50 BYTE), 
	"WRITEDAY" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table CAL
--------------------------------------------------------

  CREATE TABLE "JUXXI"."CAL" 
   (	"WEEK" VARCHAR2(1 BYTE), 
	"DAY" VARCHAR2(2 BYTE), 
	"NUM_DAY" VARCHAR2(2 BYTE)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table CART1
--------------------------------------------------------

  CREATE TABLE "JUXXI"."CART1" 
   (	"IDX" NUMBER(5,0), 
	"NUM" NUMBER(5,0), 
	"CNT" NUMBER(5,0), 
	"GUIPDAY" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table CART2
--------------------------------------------------------

  CREATE TABLE "JUXXI"."CART2" 
   (	"IDX" NUMBER(5,0), 
	"NUM" NUMBER(5,0), 
	"CNT" NUMBER(5,0), 
	"GUIPDAY" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table DEPARTMENT
--------------------------------------------------------

  CREATE TABLE "JUXXI"."DEPARTMENT" 
   (	"DEPTNO" NUMBER(3,0), 
	"DNAME" VARCHAR2(20 BYTE), 
	"PART" NUMBER(3,0), 
	"BUILD" VARCHAR2(14 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table DEPT
--------------------------------------------------------

  CREATE TABLE "JUXXI"."DEPT" 
   (	"DEPTNO" NUMBER(2,0), 
	"DNAME" VARCHAR2(14 BYTE), 
	"LOC" VARCHAR2(13 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table DEPT2
--------------------------------------------------------

  CREATE TABLE "JUXXI"."DEPT2" 
   (	"DCODE" VARCHAR2(6 BYTE), 
	"DNAME" VARCHAR2(20 BYTE), 
	"PDEPT" VARCHAR2(6 BYTE), 
	"AREA" VARCHAR2(16 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table DML_ERR_TEST
--------------------------------------------------------

  CREATE TABLE "JUXXI"."DML_ERR_TEST" 
   (	"NO" NUMBER, 
	"NAME" VARCHAR2(10 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table EMP
--------------------------------------------------------

  CREATE TABLE "JUXXI"."EMP" 
   (	"EMPNO" NUMBER(4,0), 
	"ENAME" VARCHAR2(10 BYTE), 
	"JOB" VARCHAR2(9 BYTE), 
	"MGR" NUMBER(4,0), 
	"HIREDATE" DATE, 
	"SAL" NUMBER(7,2), 
	"COMM" NUMBER(7,2), 
	"DEPTNO" NUMBER(2,0), 
	"TOTSAL" NUMBER(30,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table EMP2
--------------------------------------------------------

  CREATE TABLE "JUXXI"."EMP2" 
   (	"EMPNO" NUMBER, 
	"NAME" VARCHAR2(10 BYTE), 
	"BIRTHDAY" DATE, 
	"DEPTNO" VARCHAR2(6 BYTE), 
	"EMP_TYPE" VARCHAR2(8 BYTE), 
	"TEL" VARCHAR2(15 BYTE), 
	"HOBBY" VARCHAR2(30 BYTE), 
	"PAY" NUMBER, 
	"POSITION" VARCHAR2(8 BYTE), 
	"PEMPNO" NUMBER
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table EXAM_01
--------------------------------------------------------

  CREATE TABLE "JUXXI"."EXAM_01" 
   (	"STUDNO" NUMBER, 
	"TOTAL" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table FOODMENU
--------------------------------------------------------

  CREATE TABLE "JUXXI"."FOODMENU" 
   (	"FNO" NUMBER(7,0), 
	"FOOD_NAME" VARCHAR2(30 BYTE), 
	"PRICE" NUMBER(30,0), 
	"SHOP_NAME" VARCHAR2(20 BYTE), 
	"LOC" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table FOODORDER
--------------------------------------------------------

  CREATE TABLE "JUXXI"."FOODORDER" 
   (	"NO" NUMBER(5,0), 
	"ORDER_NAME" VARCHAR2(20 BYTE), 
	"FNO" NUMBER(7,0), 
	"ADDR" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table GIFT
--------------------------------------------------------

  CREATE TABLE "JUXXI"."GIFT" 
   (	"GNO" NUMBER, 
	"GNAME" VARCHAR2(15 BYTE), 
	"G_START" NUMBER, 
	"G_END" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table GOGAK
--------------------------------------------------------

  CREATE TABLE "JUXXI"."GOGAK" 
   (	"GNO" NUMBER(8,0), 
	"GNAME" VARCHAR2(12 BYTE), 
	"JUMIN" CHAR(13 BYTE), 
	"POINT" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table HAKJUM
--------------------------------------------------------

  CREATE TABLE "JUXXI"."HAKJUM" 
   (	"GRADE" CHAR(3 BYTE), 
	"MIN_POINT" NUMBER, 
	"MAX_POINT" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table HELLO
--------------------------------------------------------

  CREATE TABLE "JUXXI"."HELLO" 
   (	"NUM" NUMBER(5,0), 
	"NAME" VARCHAR2(20 BYTE), 
	"ADDR" VARCHAR2(30 BYTE), 
	"SDATE" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table INFO
--------------------------------------------------------

  CREATE TABLE "JUXXI"."INFO" 
   (	"NUM" NUMBER(5,0), 
	"NAME" VARCHAR2(20 BYTE), 
	"JOB" VARCHAR2(30 BYTE), 
	"GENDER" VARCHAR2(10 BYTE), 
	"AGE" NUMBER(5,0), 
	"HP" VARCHAR2(20 BYTE), 
	"IPSADAY" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table INFO2
--------------------------------------------------------

  CREATE TABLE "JUXXI"."INFO2" 
   (	"NUM" NUMBER(5,0), 
	"NAME" VARCHAR2(20 BYTE), 
	"JOB" VARCHAR2(30 BYTE), 
	"GENDER" VARCHAR2(10 BYTE), 
	"AGE" NUMBER(5,0), 
	"HANDPHONE" VARCHAR2(20 BYTE), 
	"IPSADAY" DATE, 
	"ADDR" VARCHAR2(30 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table MEMBER
--------------------------------------------------------

  CREATE TABLE "JUXXI"."MEMBER" 
   (	"NO" NUMBER(4,0), 
	"NAME" VARCHAR2(10 BYTE), 
	"JUMIN" CHAR(13 BYTE), 
	"PASSWD" VARCHAR2(10 BYTE), 
	"ID" VARCHAR2(15 BYTE), 
	"AN_KEY" VARCHAR2(15 BYTE), 
	"AN_KEY_DAP" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table MYSHOP
--------------------------------------------------------

  CREATE TABLE "JUXXI"."MYSHOP" 
   (	"NO" NUMBER(5,0), 
	"SANGPUM" VARCHAR2(30 BYTE), 
	"SU" NUMBER(10,0), 
	"PRICE" NUMBER(10,0), 
	"SIZE1" VARCHAR2(30 BYTE), 
	"IPGODAY" DATE DEFAULT sysdate
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table NEW_CAR
--------------------------------------------------------

  CREATE TABLE "JUXXI"."NEW_CAR" 
   (	"NUM" NUMBER(5,0), 
	"CAR_NAME" VARCHAR2(20 BYTE), 
	"CAR_MADE" VARCHAR2(20 BYTE), 
	"CAR_COLOR" VARCHAR2(50 BYTE), 
	"CAR_PAY" NUMBER(10,0), 
	"CAR_FUEL" NUMBER(5,0), 
	"CAR_DAY" DATE
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table PANMAE
--------------------------------------------------------

  CREATE TABLE "JUXXI"."PANMAE" 
   (	"P_DATE" VARCHAR2(8 BYTE), 
	"P_CODE" NUMBER, 
	"P_QTY" NUMBER, 
	"P_TOTAL" NUMBER, 
	"P_STORE" VARCHAR2(5 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table PRODUCT
--------------------------------------------------------

  CREATE TABLE "JUXXI"."PRODUCT" 
   (	"P_CODE" NUMBER(3,0), 
	"P_NAME" VARCHAR2(20 BYTE), 
	"P_PRICE" NUMBER
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table PROFESSOR
--------------------------------------------------------

  CREATE TABLE "JUXXI"."PROFESSOR" 
   (	"PROFNO" NUMBER(4,0), 
	"NAME" VARCHAR2(10 BYTE), 
	"ID" VARCHAR2(15 BYTE), 
	"POSITION" VARCHAR2(10 BYTE), 
	"PAY" NUMBER(3,0), 
	"HIREDATE" DATE, 
	"BONUS" NUMBER(4,0), 
	"DEPTNO" NUMBER(3,0), 
	"EMAIL" VARCHAR2(50 BYTE), 
	"HPAGE" VARCHAR2(50 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table PT_01
--------------------------------------------------------

  CREATE TABLE "JUXXI"."PT_01" 
   (	"�먮ℓ踰덊샇" VARCHAR2(8 BYTE), 
	"�쒗뭹踰덊샇" CHAR(4 BYTE), 
	"�섎웾" NUMBER, 
	"湲덉븸" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table PT_02
--------------------------------------------------------

  CREATE TABLE "JUXXI"."PT_02" 
   (	"�먮ℓ踰덊샇" VARCHAR2(8 BYTE), 
	"�쒗뭹踰덊샇" CHAR(4 BYTE), 
	"�섎웾" NUMBER, 
	"湲덉븸" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table P_01
--------------------------------------------------------

  CREATE TABLE "JUXXI"."P_01" 
   (	"NO" NUMBER, 
	"NAME" VARCHAR2(10 BYTE)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table P_02
--------------------------------------------------------

  CREATE TABLE "JUXXI"."P_02" 
   (	"NO" NUMBER, 
	"NAME" VARCHAR2(10 BYTE)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table P_GRADE
--------------------------------------------------------

  CREATE TABLE "JUXXI"."P_GRADE" 
   (	"POSITION" VARCHAR2(10 BYTE), 
	"S_AGE" NUMBER, 
	"E_AGE" NUMBER, 
	"S_YEAR" NUMBER, 
	"E_YEAR" NUMBER, 
	"S_PAY" NUMBER, 
	"E_PAY" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table P_TOTAL
--------------------------------------------------------

  CREATE TABLE "JUXXI"."P_TOTAL" 
   (	"�먮ℓ踰덊샇" VARCHAR2(8 BYTE), 
	"�쒗뭹踰덊샇" CHAR(4 BYTE), 
	"�섎웾" NUMBER, 
	"湲덉븸" NUMBER
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table REG_TEST
--------------------------------------------------------

  CREATE TABLE "JUXXI"."REG_TEST" 
   (	"TEXT" VARCHAR2(10 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table SALES
--------------------------------------------------------

  CREATE TABLE "JUXXI"."SALES" 
   (	"NUM" NUMBER(5,0), 
	"TYPE" VARCHAR2(10 BYTE), 
	"SANGPUM" VARCHAR2(30 BYTE), 
	"SU" NUMBER(5,0), 
	"DAN" NUMBER(5,0), 
	"IPGODAY" DATE
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table SAWON
--------------------------------------------------------

  CREATE TABLE "JUXXI"."SAWON" 
   (	"NUM" NUMBER(5,0), 
	"NAME" VARCHAR2(20 BYTE), 
	"GENDER" VARCHAR2(20 BYTE), 
	"BUSEO" VARCHAR2(20 BYTE), 
	"PAY" NUMBER(10,0) DEFAULT 1200000
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table SHOP
--------------------------------------------------------

  CREATE TABLE "JUXXI"."SHOP" 
   (	"NUM" NUMBER(5,0), 
	"SANGPUM" VARCHAR2(30 BYTE), 
	"COLOR" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table STUDENT
--------------------------------------------------------

  CREATE TABLE "JUXXI"."STUDENT" 
   (	"STUDNO" NUMBER(4,0), 
	"NAME" VARCHAR2(10 BYTE), 
	"ID" VARCHAR2(20 BYTE), 
	"GRADE" NUMBER, 
	"JUMIN" CHAR(13 BYTE), 
	"BIRTHDAY" DATE, 
	"TEL" VARCHAR2(15 BYTE), 
	"HEIGHT" NUMBER(4,0), 
	"WEIGHT" NUMBER(3,0), 
	"DEPTNO1" NUMBER(3,0), 
	"DEPTNO2" NUMBER(3,0), 
	"PROFNO" NUMBER(4,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table TEST
--------------------------------------------------------

  CREATE TABLE "JUXXI"."TEST" 
   (	"NUM" NUMBER(5,0), 
	"NAME" VARCHAR2(20 BYTE), 
	"SCORE" NUMBER(6,2), 
	"BIRTH" DATE, 
	"ADDR" VARCHAR2(50 BYTE) DEFAULT '강남구'
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table TEST_ENABLE
--------------------------------------------------------

  CREATE TABLE "JUXXI"."TEST_ENABLE" 
   (	"NO" NUMBER, 
	"NAME" VARCHAR2(10 BYTE)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table TEST_NOVALIDATE
--------------------------------------------------------

  CREATE TABLE "JUXXI"."TEST_NOVALIDATE" 
   (	"NO" NUMBER, 
	"NAME" VARCHAR2(10 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table TEST_VALIDATE
--------------------------------------------------------

  CREATE TABLE "JUXXI"."TEST_VALIDATE" 
   (	"NO" NUMBER, 
	"NAME" VARCHAR2(10 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
REM INSERTING into JUXXI.ANSWER
SET DEFINE OFF;
Insert into JUXXI.ANSWER (NUM,BNO,NICKNAME,CONTENT) values (21,2,'대장','반가워요');
Insert into JUXXI.ANSWER (NUM,BNO,NICKNAME,CONTENT) values (22,1,'성지니','안녕하세요');
Insert into JUXXI.ANSWER (NUM,BNO,NICKNAME,CONTENT) values (23,4,'빵쥐','와우');
Insert into JUXXI.ANSWER (NUM,BNO,NICKNAME,CONTENT) values (24,3,'먹투어','샌드위치!');
Insert into JUXXI.ANSWER (NUM,BNO,NICKNAME,CONTENT) values (25,5,'루아','사람 ㅎㄷㄷ');
Insert into JUXXI.ANSWER (NUM,BNO,NICKNAME,CONTENT) values (26,1,'성지니','안녕하세요');
Insert into JUXXI.ANSWER (NUM,BNO,NICKNAME,CONTENT) values (27,4,'빵쥐','와우');
Insert into JUXXI.ANSWER (NUM,BNO,NICKNAME,CONTENT) values (28,3,'먹투어','샌드위치!');
Insert into JUXXI.ANSWER (NUM,BNO,NICKNAME,CONTENT) values (29,5,'루아','사람 ㅎㄷㄷ');
REM INSERTING into JUXXI.BOARD
SET DEFINE OFF;
Insert into JUXXI.BOARD (BNO,WRITER,SUBJECT,WRITEDAY) values (1,'오늘도 열심히','안녕하세요',to_date('25/03/19','RR/MM/DD'));
Insert into JUXXI.BOARD (BNO,WRITER,SUBJECT,WRITEDAY) values (2,'1댕','오늘가입했어요',to_date('25/03/19','RR/MM/DD'));
Insert into JUXXI.BOARD (BNO,WRITER,SUBJECT,WRITEDAY) values (3,'점메추','배고파요',to_date('25/03/19','RR/MM/DD'));
Insert into JUXXI.BOARD (BNO,WRITER,SUBJECT,WRITEDAY) values (4,'야미','빵투어',to_date('25/03/19','RR/MM/DD'));
Insert into JUXXI.BOARD (BNO,WRITER,SUBJECT,WRITEDAY) values (5,'아담','팝업후기',to_date('25/03/19','RR/MM/DD'));
REM INSERTING into JUXXI.CAL
SET DEFINE OFF;
REM INSERTING into JUXXI.CART1
SET DEFINE OFF;
Insert into JUXXI.CART1 (IDX,NUM,CNT,GUIPDAY) values (10,2,1,to_date('25/03/19','RR/MM/DD'));
Insert into JUXXI.CART1 (IDX,NUM,CNT,GUIPDAY) values (11,1,2,to_date('25/03/19','RR/MM/DD'));
Insert into JUXXI.CART1 (IDX,NUM,CNT,GUIPDAY) values (12,5,3,to_date('25/03/19','RR/MM/DD'));
REM INSERTING into JUXXI.CART2
SET DEFINE OFF;
Insert into JUXXI.CART2 (IDX,NUM,CNT,GUIPDAY) values (13,2,1,to_date('25/03/19','RR/MM/DD'));
Insert into JUXXI.CART2 (IDX,NUM,CNT,GUIPDAY) values (14,1,2,to_date('25/03/19','RR/MM/DD'));
Insert into JUXXI.CART2 (IDX,NUM,CNT,GUIPDAY) values (15,5,3,to_date('25/03/19','RR/MM/DD'));
Insert into JUXXI.CART2 (IDX,NUM,CNT,GUIPDAY) values (16,2,1,to_date('25/03/19','RR/MM/DD'));
Insert into JUXXI.CART2 (IDX,NUM,CNT,GUIPDAY) values (17,2,6,to_date('25/03/19','RR/MM/DD'));
Insert into JUXXI.CART2 (IDX,NUM,CNT,GUIPDAY) values (18,1,5,to_date('25/03/19','RR/MM/DD'));
REM INSERTING into JUXXI.DEPARTMENT
SET DEFINE OFF;
Insert into JUXXI.DEPARTMENT (DEPTNO,DNAME,PART,BUILD) values (101,'컴퓨터공학과',100,'정보관');
Insert into JUXXI.DEPARTMENT (DEPTNO,DNAME,PART,BUILD) values (301,'문헌정보학과',300,'인문관');
Insert into JUXXI.DEPARTMENT (DEPTNO,DNAME,PART,BUILD) values (300,'인문사회학부',20,null);
Insert into JUXXI.DEPARTMENT (DEPTNO,DNAME,PART,BUILD) values (102,'유아교육과',null,null);
Insert into JUXXI.DEPARTMENT (DEPTNO,DNAME,PART,BUILD) values (103,'마술교육과',null,null);
Insert into JUXXI.DEPARTMENT (DEPTNO,DNAME,PART,BUILD) values (201,'영문학과',null,null);
Insert into JUXXI.DEPARTMENT (DEPTNO,DNAME,PART,BUILD) values (202,'국문학과',null,null);
REM INSERTING into JUXXI.DEPT
SET DEFINE OFF;
Insert into JUXXI.DEPT (DEPTNO,DNAME,LOC) values (10,'ACCOUNTING','NEW YORK');
Insert into JUXXI.DEPT (DEPTNO,DNAME,LOC) values (20,'RESEARCH','DALLAS');
Insert into JUXXI.DEPT (DEPTNO,DNAME,LOC) values (30,'SALES','CHICAGO');
Insert into JUXXI.DEPT (DEPTNO,DNAME,LOC) values (40,'OPERATIONS','BOSTON');
REM INSERTING into JUXXI.DEPT2
SET DEFINE OFF;
REM INSERTING into JUXXI.DML_ERR_TEST
SET DEFINE OFF;
Insert into JUXXI.DML_ERR_TEST (NO,NAME) values (1,'AAA');
Insert into JUXXI.DML_ERR_TEST (NO,NAME) values (2,'BBB');
REM INSERTING into JUXXI.EMP
SET DEFINE OFF;
Insert into JUXXI.EMP (EMPNO,ENAME,JOB,MGR,HIREDATE,SAL,COMM,DEPTNO,TOTSAL) values (7369,'SMITH','CLERK',7902,to_date('80/12/17','RR/MM/DD'),800,null,20,800);
Insert into JUXXI.EMP (EMPNO,ENAME,JOB,MGR,HIREDATE,SAL,COMM,DEPTNO,TOTSAL) values (7499,'ALLEN','SALESMAN',7698,to_date('81/02/20','RR/MM/DD'),1600,300,30,1900);
Insert into JUXXI.EMP (EMPNO,ENAME,JOB,MGR,HIREDATE,SAL,COMM,DEPTNO,TOTSAL) values (7521,'WARD','SALESMAN',7698,to_date('82/02/22','RR/MM/DD'),1250,500,30,1750);
Insert into JUXXI.EMP (EMPNO,ENAME,JOB,MGR,HIREDATE,SAL,COMM,DEPTNO,TOTSAL) values (7566,'JONES','MANAGER',7839,to_date('81/04/02','RR/MM/DD'),2975,null,20,2975);
Insert into JUXXI.EMP (EMPNO,ENAME,JOB,MGR,HIREDATE,SAL,COMM,DEPTNO,TOTSAL) values (7654,'MARTIN','SALESMAN',7698,to_date('81/09/28','RR/MM/DD'),1250,1400,30,2650);
Insert into JUXXI.EMP (EMPNO,ENAME,JOB,MGR,HIREDATE,SAL,COMM,DEPTNO,TOTSAL) values (7698,'BLAKE','MANAGER',7839,to_date('81/05/01','RR/MM/DD'),2850,null,30,2850);
Insert into JUXXI.EMP (EMPNO,ENAME,JOB,MGR,HIREDATE,SAL,COMM,DEPTNO,TOTSAL) values (7782,'CLARK','MANAGER',7839,to_date('81/06/09','RR/MM/DD'),2450,null,10,2450);
Insert into JUXXI.EMP (EMPNO,ENAME,JOB,MGR,HIREDATE,SAL,COMM,DEPTNO,TOTSAL) values (7788,'SCOTT','ANALYST',7566,to_date('87/04/17','RR/MM/DD'),3000,null,20,3000);
Insert into JUXXI.EMP (EMPNO,ENAME,JOB,MGR,HIREDATE,SAL,COMM,DEPTNO,TOTSAL) values (7839,'KING','PRESIDENT',null,to_date('81/11/17','RR/MM/DD'),5000,null,10,5000);
Insert into JUXXI.EMP (EMPNO,ENAME,JOB,MGR,HIREDATE,SAL,COMM,DEPTNO,TOTSAL) values (7844,'TURNER','SALESMAN',7698,to_date('81/09/08','RR/MM/DD'),1500,0,30,1500);
Insert into JUXXI.EMP (EMPNO,ENAME,JOB,MGR,HIREDATE,SAL,COMM,DEPTNO,TOTSAL) values (7876,'ADAMS','CLERK',7788,to_date('87/05/23','RR/MM/DD'),1100,null,20,1100);
Insert into JUXXI.EMP (EMPNO,ENAME,JOB,MGR,HIREDATE,SAL,COMM,DEPTNO,TOTSAL) values (7900,'JAMES','CLERK',7698,to_date('81/12/03','RR/MM/DD'),950,null,30,950);
Insert into JUXXI.EMP (EMPNO,ENAME,JOB,MGR,HIREDATE,SAL,COMM,DEPTNO,TOTSAL) values (7902,'FORD','ANALYST',7566,to_date('81/12/03','RR/MM/DD'),3000,null,20,3000);
Insert into JUXXI.EMP (EMPNO,ENAME,JOB,MGR,HIREDATE,SAL,COMM,DEPTNO,TOTSAL) values (7934,'MILLER','CLERK',7782,to_date('82/01/23','RR/MM/DD'),1300,null,10,1300);
REM INSERTING into JUXXI.EMP2
SET DEFINE OFF;
REM INSERTING into JUXXI.EXAM_01
SET DEFINE OFF;
Insert into JUXXI.EXAM_01 (STUDNO,TOTAL) values (9411,97);
Insert into JUXXI.EXAM_01 (STUDNO,TOTAL) values (9412,78);
Insert into JUXXI.EXAM_01 (STUDNO,TOTAL) values (9413,83);
Insert into JUXXI.EXAM_01 (STUDNO,TOTAL) values (9414,62);
Insert into JUXXI.EXAM_01 (STUDNO,TOTAL) values (9415,88);
Insert into JUXXI.EXAM_01 (STUDNO,TOTAL) values (9511,92);
Insert into JUXXI.EXAM_01 (STUDNO,TOTAL) values (9512,87);
Insert into JUXXI.EXAM_01 (STUDNO,TOTAL) values (9513,81);
Insert into JUXXI.EXAM_01 (STUDNO,TOTAL) values (9514,79);
Insert into JUXXI.EXAM_01 (STUDNO,TOTAL) values (9515,95);
Insert into JUXXI.EXAM_01 (STUDNO,TOTAL) values (9611,89);
Insert into JUXXI.EXAM_01 (STUDNO,TOTAL) values (9612,77);
Insert into JUXXI.EXAM_01 (STUDNO,TOTAL) values (9613,86);
Insert into JUXXI.EXAM_01 (STUDNO,TOTAL) values (9614,82);
Insert into JUXXI.EXAM_01 (STUDNO,TOTAL) values (9615,87);
Insert into JUXXI.EXAM_01 (STUDNO,TOTAL) values (9711,91);
Insert into JUXXI.EXAM_01 (STUDNO,TOTAL) values (9712,88);
Insert into JUXXI.EXAM_01 (STUDNO,TOTAL) values (9713,82);
Insert into JUXXI.EXAM_01 (STUDNO,TOTAL) values (9714,83);
Insert into JUXXI.EXAM_01 (STUDNO,TOTAL) values (9715,84);
REM INSERTING into JUXXI.FOODMENU
SET DEFINE OFF;
Insert into JUXXI.FOODMENU (FNO,FOOD_NAME,PRICE,SHOP_NAME,LOC) values (1,'알리오올리오',17000,'호담','역삼동');
Insert into JUXXI.FOODMENU (FNO,FOOD_NAME,PRICE,SHOP_NAME,LOC) values (4,'까르보나라',19000,'허쉬','방배동');
Insert into JUXXI.FOODMENU (FNO,FOOD_NAME,PRICE,SHOP_NAME,LOC) values (7,'필라프',18000,'엔젤','역삼동');
Insert into JUXXI.FOODMENU (FNO,FOOD_NAME,PRICE,SHOP_NAME,LOC) values (10,'피자',22000,'아키','서초동');
Insert into JUXXI.FOODMENU (FNO,FOOD_NAME,PRICE,SHOP_NAME,LOC) values (13,'스테이크',37000,'수피아','논현동');
REM INSERTING into JUXXI.FOODORDER
SET DEFINE OFF;
Insert into JUXXI.FOODORDER (NO,ORDER_NAME,FNO,ADDR) values (16,'안정아',1,'역삼동');
Insert into JUXXI.FOODORDER (NO,ORDER_NAME,FNO,ADDR) values (19,'하지웅',4,'논현동');
Insert into JUXXI.FOODORDER (NO,ORDER_NAME,FNO,ADDR) values (28,'안정아',1,'역삼동');
Insert into JUXXI.FOODORDER (NO,ORDER_NAME,FNO,ADDR) values (31,'하지웅',4,'논현동');
Insert into JUXXI.FOODORDER (NO,ORDER_NAME,FNO,ADDR) values (40,'안정아',1,'역삼동');
Insert into JUXXI.FOODORDER (NO,ORDER_NAME,FNO,ADDR) values (43,'하지웅',4,'논현동');
Insert into JUXXI.FOODORDER (NO,ORDER_NAME,FNO,ADDR) values (46,'구준희',7,'방배동');
Insert into JUXXI.FOODORDER (NO,ORDER_NAME,FNO,ADDR) values (49,'이주연',10,'역삼동');
REM INSERTING into JUXXI.GIFT
SET DEFINE OFF;
REM INSERTING into JUXXI.GOGAK
SET DEFINE OFF;
Insert into JUXXI.GOGAK (GNO,GNAME,JUMIN,POINT) values (20010020,'�덉슦','7802232116784',730000);
REM INSERTING into JUXXI.HAKJUM
SET DEFINE OFF;
Insert into JUXXI.HAKJUM (GRADE,MIN_POINT,MAX_POINT) values ('A+ ',96,100);
Insert into JUXXI.HAKJUM (GRADE,MIN_POINT,MAX_POINT) values ('A0 ',90,95);
Insert into JUXXI.HAKJUM (GRADE,MIN_POINT,MAX_POINT) values ('B+ ',86,89);
Insert into JUXXI.HAKJUM (GRADE,MIN_POINT,MAX_POINT) values ('B0 ',80,85);
Insert into JUXXI.HAKJUM (GRADE,MIN_POINT,MAX_POINT) values ('C+ ',76,79);
Insert into JUXXI.HAKJUM (GRADE,MIN_POINT,MAX_POINT) values ('C0 ',70,75);
Insert into JUXXI.HAKJUM (GRADE,MIN_POINT,MAX_POINT) values ('D  ',0,69);
REM INSERTING into JUXXI.HELLO
SET DEFINE OFF;
Insert into JUXXI.HELLO (NUM,NAME,ADDR,SDATE) values (21,'오스앙','서울시 관악구',to_date('25/03/20','RR/MM/DD'));
REM INSERTING into JUXXI.INFO
SET DEFINE OFF;
Insert into JUXXI.INFO (NUM,NAME,JOB,GENDER,AGE,HP,IPSADAY) values (1,'조승원','프로그래머','남자',23,'010-1111-2222',to_date('22/11/25','RR/MM/DD'));
Insert into JUXXI.INFO (NUM,NAME,JOB,GENDER,AGE,HP,IPSADAY) values (2,'조승원','프로그래머','남자',23,'010-1111-2222',to_date('22/11/25','RR/MM/DD'));
Insert into JUXXI.INFO (NUM,NAME,JOB,GENDER,AGE,HP,IPSADAY) values (3,'김민지','가수','여자',22,'010-1456-2522',to_date('21/10/05','RR/MM/DD'));
Insert into JUXXI.INFO (NUM,NAME,JOB,GENDER,AGE,HP,IPSADAY) values (4,'김민지','교사','여자',27,'010-1456-2522',to_date('21/10/05','RR/MM/DD'));
Insert into JUXXI.INFO (NUM,NAME,JOB,GENDER,AGE,HP,IPSADAY) values (5,'김민지','교사','여자',27,'010-1456-2522',to_date('21/10/05','RR/MM/DD'));
Insert into JUXXI.INFO (NUM,NAME,JOB,GENDER,AGE,HP,IPSADAY) values (6,'최수현','엔지니어','남자',29,'010-1426-2577',to_date('19/10/07','RR/MM/DD'));
Insert into JUXXI.INFO (NUM,NAME,JOB,GENDER,AGE,HP,IPSADAY) values (7,'김민준','엔지니어','남자',33,'010-1774-1832',to_date('17/07/03','RR/MM/DD'));
Insert into JUXXI.INFO (NUM,NAME,JOB,GENDER,AGE,HP,IPSADAY) values (8,'오주현','유투버','여자',26,'010-1152-8972',to_date('24/12/25','RR/MM/DD'));
Insert into JUXXI.INFO (NUM,NAME,JOB,GENDER,AGE,HP,IPSADAY) values (9,'이주언','프로그래머','여자',28,'010-3556-2547',to_date('22/01/06','RR/MM/DD'));
Insert into JUXXI.INFO (NUM,NAME,JOB,GENDER,AGE,HP,IPSADAY) values (10,'이주언','프로그래머','여자',28,'010-3556-2547',to_date('22/01/06','RR/MM/DD'));
Insert into JUXXI.INFO (NUM,NAME,JOB,GENDER,AGE,HP,IPSADAY) values (11,'허정민','교사','남자',39,'010-2756-2599',to_date('15/12/23','RR/MM/DD'));
Insert into JUXXI.INFO (NUM,NAME,JOB,GENDER,AGE,HP,IPSADAY) values (12,'강민주','엔지니어','여자',25,'010-3689-2446',to_date('24/11/17','RR/MM/DD'));
Insert into JUXXI.INFO (NUM,NAME,JOB,GENDER,AGE,HP,IPSADAY) values (13,'최성민','프로그래머','남자',34,'010-98576-4252',to_date('18/04/05','RR/MM/DD'));
Insert into JUXXI.INFO (NUM,NAME,JOB,GENDER,AGE,HP,IPSADAY) values (14,'안주은','운동선수','여자',32,'010-7869-4362',to_date('19/05/07','RR/MM/DD'));
REM INSERTING into JUXXI.INFO2
SET DEFINE OFF;
Insert into JUXXI.INFO2 (NUM,NAME,JOB,GENDER,AGE,HANDPHONE,IPSADAY,ADDR) values (1,'조승원','프로그래머','남자',23,'010-1111-2222',to_date('22/11/25','RR/MM/DD'),null);
Insert into JUXXI.INFO2 (NUM,NAME,JOB,GENDER,AGE,HANDPHONE,IPSADAY,ADDR) values (2,'조승원','프로그래머','남자',23,'010-1111-2222',to_date('22/11/25','RR/MM/DD'),null);
Insert into JUXXI.INFO2 (NUM,NAME,JOB,GENDER,AGE,HANDPHONE,IPSADAY,ADDR) values (7,'김민준','엔지니어','남자',33,'010-1774-1832',to_date('17/07/03','RR/MM/DD'),null);
Insert into JUXXI.INFO2 (NUM,NAME,JOB,GENDER,AGE,HANDPHONE,IPSADAY,ADDR) values (13,'최성민','프로그래머','남자',34,'010-98576-4252',to_date('18/04/05','RR/MM/DD'),null);
Insert into JUXXI.INFO2 (NUM,NAME,JOB,GENDER,AGE,HANDPHONE,IPSADAY,ADDR) values (15,'이현아','무용가','여자',null,null,null,'관악구');
Insert into JUXXI.INFO2 (NUM,NAME,JOB,GENDER,AGE,HANDPHONE,IPSADAY,ADDR) values (16,'이현아','무용가','여자',null,null,null,'관악구');
Insert into JUXXI.INFO2 (NUM,NAME,JOB,GENDER,AGE,HANDPHONE,IPSADAY,ADDR) values (17,'이현아','무용가','여자',null,null,null,'관악구');
Insert into JUXXI.INFO2 (NUM,NAME,JOB,GENDER,AGE,HANDPHONE,IPSADAY,ADDR) values (18,'이현아','무용가','여자',null,null,null,'관악구');
Insert into JUXXI.INFO2 (NUM,NAME,JOB,GENDER,AGE,HANDPHONE,IPSADAY,ADDR) values (19,'이현아','무용가','여자',null,null,null,'관악구');
REM INSERTING into JUXXI.MEMBER
SET DEFINE OFF;
REM INSERTING into JUXXI.MYSHOP
SET DEFINE OFF;
Insert into JUXXI.MYSHOP (NO,SANGPUM,SU,PRICE,SIZE1,IPGODAY) values (3,'스커트',10,50000,'s',to_date('25/03/17','RR/MM/DD'));
Insert into JUXXI.MYSHOP (NO,SANGPUM,SU,PRICE,SIZE1,IPGODAY) values (5,'청바지',25,64000,'m',to_date('25/03/17','RR/MM/DD'));
Insert into JUXXI.MYSHOP (NO,SANGPUM,SU,PRICE,SIZE1,IPGODAY) values (7,'가방',16,75000,'m',to_date('25/03/17','RR/MM/DD'));
Insert into JUXXI.MYSHOP (NO,SANGPUM,SU,PRICE,SIZE1,IPGODAY) values (9,'티셔츠',34,22000,'xl',to_date('25/03/17','RR/MM/DD'));
Insert into JUXXI.MYSHOP (NO,SANGPUM,SU,PRICE,SIZE1,IPGODAY) values (11,'패딩',19,160000,'m',to_date('25/03/17','RR/MM/DD'));
REM INSERTING into JUXXI.NEW_CAR
SET DEFINE OFF;
REM INSERTING into JUXXI.PANMAE
SET DEFINE OFF;
Insert into JUXXI.PANMAE (P_DATE,P_CODE,P_QTY,P_TOTAL,P_STORE) values ('20110101',100,3,2400,'1000');
Insert into JUXXI.PANMAE (P_DATE,P_CODE,P_QTY,P_TOTAL,P_STORE) values ('20110101',101,5,4500,'1001');
Insert into JUXXI.PANMAE (P_DATE,P_CODE,P_QTY,P_TOTAL,P_STORE) values ('20110101',102,2,2000,'1003');
Insert into JUXXI.PANMAE (P_DATE,P_CODE,P_QTY,P_TOTAL,P_STORE) values ('20110101',103,6,5400,'1004');
Insert into JUXXI.PANMAE (P_DATE,P_CODE,P_QTY,P_TOTAL,P_STORE) values ('20110102',102,2,2000,'1000');
Insert into JUXXI.PANMAE (P_DATE,P_CODE,P_QTY,P_TOTAL,P_STORE) values ('20110102',103,5,4500,'1002');
Insert into JUXXI.PANMAE (P_DATE,P_CODE,P_QTY,P_TOTAL,P_STORE) values ('20110102',104,3,2400,'1002');
Insert into JUXXI.PANMAE (P_DATE,P_CODE,P_QTY,P_TOTAL,P_STORE) values ('20110102',105,2,3000,'1000');
Insert into JUXXI.PANMAE (P_DATE,P_CODE,P_QTY,P_TOTAL,P_STORE) values ('20110103',100,10,8000,'1004');
Insert into JUXXI.PANMAE (P_DATE,P_CODE,P_QTY,P_TOTAL,P_STORE) values ('20110103',100,2,1600,'1000');
Insert into JUXXI.PANMAE (P_DATE,P_CODE,P_QTY,P_TOTAL,P_STORE) values ('20110103',100,3,2400,'1001');
Insert into JUXXI.PANMAE (P_DATE,P_CODE,P_QTY,P_TOTAL,P_STORE) values ('20110103',101,4,3600,'1003');
Insert into JUXXI.PANMAE (P_DATE,P_CODE,P_QTY,P_TOTAL,P_STORE) values ('20110104',100,2,1600,'1002');
Insert into JUXXI.PANMAE (P_DATE,P_CODE,P_QTY,P_TOTAL,P_STORE) values ('20110104',100,4,3200,'1003');
Insert into JUXXI.PANMAE (P_DATE,P_CODE,P_QTY,P_TOTAL,P_STORE) values ('20110104',100,5,4000,'1004');
Insert into JUXXI.PANMAE (P_DATE,P_CODE,P_QTY,P_TOTAL,P_STORE) values ('20110104',101,3,2700,'1001');
Insert into JUXXI.PANMAE (P_DATE,P_CODE,P_QTY,P_TOTAL,P_STORE) values ('20110104',101,4,3600,'1002');
Insert into JUXXI.PANMAE (P_DATE,P_CODE,P_QTY,P_TOTAL,P_STORE) values ('20110104',101,3,2700,'1003');
Insert into JUXXI.PANMAE (P_DATE,P_CODE,P_QTY,P_TOTAL,P_STORE) values ('20110104',102,4,4000,'1001');
Insert into JUXXI.PANMAE (P_DATE,P_CODE,P_QTY,P_TOTAL,P_STORE) values ('20110104',102,2,2000,'1002');
Insert into JUXXI.PANMAE (P_DATE,P_CODE,P_QTY,P_TOTAL,P_STORE) values ('20110104',103,2,1800,'1003');
REM INSERTING into JUXXI.PRODUCT
SET DEFINE OFF;
REM INSERTING into JUXXI.PROFESSOR
SET DEFINE OFF;
REM INSERTING into JUXXI.PT_01
SET DEFINE OFF;
Insert into JUXXI.PT_01 ("�먮ℓ踰덊샇","�쒗뭹踰덊샇","�섎웾","湲덉븸") values ('12010101','1000',1,500);
Insert into JUXXI.PT_01 ("�먮ℓ踰덊샇","�쒗뭹踰덊샇","�섎웾","湲덉븸") values ('12010102','1001',1,400);
Insert into JUXXI.PT_01 ("�먮ℓ踰덊샇","�쒗뭹踰덊샇","�섎웾","湲덉븸") values ('12010103','1003',1,300);
REM INSERTING into JUXXI.PT_02
SET DEFINE OFF;
Insert into JUXXI.PT_02 ("�먮ℓ踰덊샇","�쒗뭹踰덊샇","�섎웾","湲덉븸") values ('12010201','1004',1,600);
Insert into JUXXI.PT_02 ("�먮ℓ踰덊샇","�쒗뭹踰덊샇","�섎웾","湲덉븸") values ('12010202','1000',1,500);
Insert into JUXXI.PT_02 ("�먮ℓ踰덊샇","�쒗뭹踰덊샇","�섎웾","湲덉븸") values ('12010203','1005',1,700);
REM INSERTING into JUXXI.P_01
SET DEFINE OFF;
REM INSERTING into JUXXI.P_02
SET DEFINE OFF;
REM INSERTING into JUXXI.P_GRADE
SET DEFINE OFF;
Insert into JUXXI.P_GRADE (POSITION,S_AGE,E_AGE,S_YEAR,E_YEAR,S_PAY,E_PAY) values ('二쇱엫',0,24,1,2,12000000,29990000);
Insert into JUXXI.P_GRADE (POSITION,S_AGE,E_AGE,S_YEAR,E_YEAR,S_PAY,E_PAY) values ('怨쇱옣',29,32,6,8,45010000,51000000);
Insert into JUXXI.P_GRADE (POSITION,S_AGE,E_AGE,S_YEAR,E_YEAR,S_PAY,E_PAY) values ('李⑥옣',33,36,9,10,51010000,60000000);
Insert into JUXXI.P_GRADE (POSITION,S_AGE,E_AGE,S_YEAR,E_YEAR,S_PAY,E_PAY) values ('�댁궗',41,55,14,99,75010000,100000000);
REM INSERTING into JUXXI.P_TOTAL
SET DEFINE OFF;
REM INSERTING into JUXXI.REG_TEST
SET DEFINE OFF;
Insert into JUXXI.REG_TEST (TEXT) values ('ABC123');
Insert into JUXXI.REG_TEST (TEXT) values ('ABC 123');
Insert into JUXXI.REG_TEST (TEXT) values ('abc 123');
Insert into JUXXI.REG_TEST (TEXT) values ('a1b2c3');
Insert into JUXXI.REG_TEST (TEXT) values ('aabbcc123');
Insert into JUXXI.REG_TEST (TEXT) values ('?/!@#$*&');
Insert into JUXXI.REG_TEST (TEXT) values ('\~*().,');
Insert into JUXXI.REG_TEST (TEXT) values ('123123');
Insert into JUXXI.REG_TEST (TEXT) values ('123abc');
REM INSERTING into JUXXI.SALES
SET DEFINE OFF;
REM INSERTING into JUXXI.SAWON
SET DEFINE OFF;
Insert into JUXXI.SAWON (NUM,NAME,GENDER,BUSEO,PAY) values (5,'김승택','남자','교육부',2700000);
Insert into JUXXI.SAWON (NUM,NAME,GENDER,BUSEO,PAY) values (6,'이주은','여자','교육부',2900000);
Insert into JUXXI.SAWON (NUM,NAME,GENDER,BUSEO,PAY) values (8,'남주아','여자','교육부',3400000);
Insert into JUXXI.SAWON (NUM,NAME,GENDER,BUSEO,PAY) values (9,'안정훈','남자','교육부',2900000);
Insert into JUXXI.SAWON (NUM,NAME,GENDER,BUSEO,PAY) values (10,'이진영','여자','개발부',3200000);
REM INSERTING into JUXXI.SHOP
SET DEFINE OFF;
Insert into JUXXI.SHOP (NUM,SANGPUM,COLOR) values (1,'안경','블랙');
Insert into JUXXI.SHOP (NUM,SANGPUM,COLOR) values (2,'운동화','화이트');
Insert into JUXXI.SHOP (NUM,SANGPUM,COLOR) values (4,'스커트','핑크');
Insert into JUXXI.SHOP (NUM,SANGPUM,COLOR) values (5,'반팔','그린');
REM INSERTING into JUXXI.STUDENT
SET DEFINE OFF;
Insert into JUXXI.STUDENT (STUDNO,NAME,ID,GRADE,JUMIN,BIRTHDAY,TEL,HEIGHT,WEIGHT,DEPTNO1,DEPTNO2,PROFNO) values (9715,'�덉슦','wooya2702',1,'7802232116784',to_date('78/02/23','RR/MM/DD'),'02)6122-2345',163,51,103,null,null);
REM INSERTING into JUXXI.TEST
SET DEFINE OFF;
Insert into JUXXI.TEST (NUM,NAME,SCORE,BIRTH,ADDR) values (1,'이상민',88.88,to_date('97/10/25','RR/MM/DD'),'강남구');
Insert into JUXXI.TEST (NUM,NAME,SCORE,BIRTH,ADDR) values (3,'손흥민',89.8,to_date('25/03/17','RR/MM/DD'),'강남구');
Insert into JUXXI.TEST (NUM,NAME,SCORE,BIRTH,ADDR) values (2,'강민주',null,null,'강남구');
Insert into JUXXI.TEST (NUM,NAME,SCORE,BIRTH,ADDR) values (5,'미나',null,null,'관악구');
REM INSERTING into JUXXI.TEST_ENABLE
SET DEFINE OFF;
REM INSERTING into JUXXI.TEST_NOVALIDATE
SET DEFINE OFF;
Insert into JUXXI.TEST_NOVALIDATE (NO,NAME) values (1,'AAA');
Insert into JUXXI.TEST_NOVALIDATE (NO,NAME) values (2,'BBB');
Insert into JUXXI.TEST_NOVALIDATE (NO,NAME) values (3,'CCC');
REM INSERTING into JUXXI.TEST_VALIDATE
SET DEFINE OFF;
Insert into JUXXI.TEST_VALIDATE (NO,NAME) values (1,'AAA');
Insert into JUXXI.TEST_VALIDATE (NO,NAME) values (2,'BBB');
Insert into JUXXI.TEST_VALIDATE (NO,NAME) values (3,'CCC');
--------------------------------------------------------
--  DDL for Index BOARD_PK_BNO
--------------------------------------------------------

  CREATE UNIQUE INDEX "JUXXI"."BOARD_PK_BNO" ON "JUXXI"."BOARD" ("BNO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index PK_DEPT
--------------------------------------------------------

  CREATE UNIQUE INDEX "JUXXI"."PK_DEPT" ON "JUXXI"."DEPT" ("DEPTNO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index TE_NO_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "JUXXI"."TE_NO_PK" ON "JUXXI"."TEST_ENABLE" ("NO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SAWON_PK_NUM
--------------------------------------------------------

  CREATE UNIQUE INDEX "JUXXI"."SAWON_PK_NUM" ON "JUXXI"."SAWON" ("NUM") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index PK_EMP
--------------------------------------------------------

  CREATE UNIQUE INDEX "JUXXI"."PK_EMP" ON "JUXXI"."EMP" ("EMPNO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index ANSER_PK_NUM
--------------------------------------------------------

  CREATE UNIQUE INDEX "JUXXI"."ANSER_PK_NUM" ON "JUXXI"."ANSWER" ("NUM") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index TV_NO_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "JUXXI"."TV_NO_PK" ON "JUXXI"."TEST_VALIDATE" ("NO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Procedure PRINT_TABLE
--------------------------------------------------------
set define off;

  CREATE OR REPLACE NONEDITIONABLE PROCEDURE "JUXXI"."PRINT_TABLE" ( p_query in varchar2 )
AUTHID CURRENT_USER
is
    l_theCursor     integer default dbms_sql.open_cursor;
    l_columnValue   varchar2(4000);
    l_status        integer;
    l_descTbl       dbms_sql.desc_tab;
    l_colCnt        number;
begin
    execute immediate
    'alter session set
        nls_date_format=''yyyy-mm-dd:hh24:mi:ss'' ';
    dbms_sql.parse(  l_theCursor,  p_query, dbms_sql.native );
    dbms_sql.describe_columns
    ( l_theCursor, l_colCnt, l_descTbl );
    for i in 1 .. l_colCnt loop
        dbms_sql.define_column
        (l_theCursor, i, l_columnValue, 4000);
    end loop;
    l_status := dbms_sql.execute(l_theCursor);
    while ( dbms_sql.fetch_rows(l_theCursor) > 0 ) loop
        for i in 1 .. l_colCnt loop
            dbms_sql.column_value
            ( l_theCursor, i, l_columnValue );
            dbms_output.put_line
            ( rpad( l_descTbl(i).col_name, 30 )
              || ': ' ||
              l_columnValue );
        end loop;
        dbms_output.put_line( '-----------------' );
    end loop;
    execute immediate
        'alter session set nls_date_format=''yyyy-mm-dd'' ';
exception
    when others then
      execute immediate
          'alter session set nls_date_format=''yyyy-mm-dd'' ';
      raise;
end;

/
--------------------------------------------------------
--  Constraints for Table DEPT
--------------------------------------------------------

  ALTER TABLE "JUXXI"."DEPT" ADD CONSTRAINT "PK_DEPT" PRIMARY KEY ("DEPTNO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table ANSWER
--------------------------------------------------------

  ALTER TABLE "JUXXI"."ANSWER" ADD CONSTRAINT "ANSER_PK_NUM" PRIMARY KEY ("NUM")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table SAWON
--------------------------------------------------------

  ALTER TABLE "JUXXI"."SAWON" ADD CONSTRAINT "SAWON_PK_NUM" PRIMARY KEY ("NUM")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "JUXXI"."SAWON" ADD CONSTRAINT "CK_SAWON_BUSEO" CHECK (buseo in ('개발부','교육부','디자인부')) ENABLE;
  ALTER TABLE "JUXXI"."SAWON" ADD CONSTRAINT "CK_SAWON_GENDER" CHECK (gender in ('남자','여자')) ENABLE;
--------------------------------------------------------
--  Constraints for Table FOODORDER
--------------------------------------------------------

  ALTER TABLE "JUXXI"."FOODORDER" ADD PRIMARY KEY ("NO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table PRODUCT
--------------------------------------------------------

  ALTER TABLE "JUXXI"."PRODUCT" MODIFY ("P_NAME" NOT NULL ENABLE);
  ALTER TABLE "JUXXI"."PRODUCT" ADD PRIMARY KEY ("P_CODE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table DML_ERR_TEST
--------------------------------------------------------

  ALTER TABLE "JUXXI"."DML_ERR_TEST" ADD PRIMARY KEY ("NO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table INFO
--------------------------------------------------------

  ALTER TABLE "JUXXI"."INFO" ADD PRIMARY KEY ("NUM")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table PANMAE
--------------------------------------------------------

  ALTER TABLE "JUXXI"."PANMAE" MODIFY ("P_DATE" NOT NULL ENABLE);
  ALTER TABLE "JUXXI"."PANMAE" MODIFY ("P_CODE" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table NEW_CAR
--------------------------------------------------------

  ALTER TABLE "JUXXI"."NEW_CAR" ADD PRIMARY KEY ("NUM")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table CART1
--------------------------------------------------------

  ALTER TABLE "JUXXI"."CART1" ADD PRIMARY KEY ("IDX")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table TEST_NOVALIDATE
--------------------------------------------------------

  ALTER TABLE "JUXXI"."TEST_NOVALIDATE" MODIFY ("NAME" NOT NULL ENABLE);
  ALTER TABLE "JUXXI"."TEST_NOVALIDATE" ADD PRIMARY KEY ("NO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table CART2
--------------------------------------------------------

  ALTER TABLE "JUXXI"."CART2" ADD PRIMARY KEY ("IDX")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table TEST_VALIDATE
--------------------------------------------------------

  ALTER TABLE "JUXXI"."TEST_VALIDATE" MODIFY ("NAME" CONSTRAINT "TV_NAME_NN" NOT NULL ENABLE);
  ALTER TABLE "JUXXI"."TEST_VALIDATE" ADD CONSTRAINT "TV_NO_PK" PRIMARY KEY ("NO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table SHOP
--------------------------------------------------------

  ALTER TABLE "JUXXI"."SHOP" ADD PRIMARY KEY ("NUM")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table PROFESSOR
--------------------------------------------------------

  ALTER TABLE "JUXXI"."PROFESSOR" MODIFY ("NAME" NOT NULL ENABLE);
  ALTER TABLE "JUXXI"."PROFESSOR" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "JUXXI"."PROFESSOR" MODIFY ("POSITION" NOT NULL ENABLE);
  ALTER TABLE "JUXXI"."PROFESSOR" MODIFY ("PAY" NOT NULL ENABLE);
  ALTER TABLE "JUXXI"."PROFESSOR" MODIFY ("HIREDATE" NOT NULL ENABLE);
  ALTER TABLE "JUXXI"."PROFESSOR" ADD PRIMARY KEY ("PROFNO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table TEST_ENABLE
--------------------------------------------------------

  ALTER TABLE "JUXXI"."TEST_ENABLE" MODIFY ("NAME" CONSTRAINT "TE_NAME_NN" NOT NULL ENABLE);
  ALTER TABLE "JUXXI"."TEST_ENABLE" ADD CONSTRAINT "TE_NO_PK" PRIMARY KEY ("NO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table FOODMENU
--------------------------------------------------------

  ALTER TABLE "JUXXI"."FOODMENU" ADD PRIMARY KEY ("FNO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table TEST
--------------------------------------------------------

  ALTER TABLE "JUXXI"."TEST" ADD PRIMARY KEY ("NUM")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table DEPT2
--------------------------------------------------------

  ALTER TABLE "JUXXI"."DEPT2" MODIFY ("DNAME" NOT NULL ENABLE);
  ALTER TABLE "JUXXI"."DEPT2" ADD PRIMARY KEY ("DCODE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table EMP
--------------------------------------------------------

  ALTER TABLE "JUXXI"."EMP" ADD CONSTRAINT "PK_EMP" PRIMARY KEY ("EMPNO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table EMP2
--------------------------------------------------------

  ALTER TABLE "JUXXI"."EMP2" MODIFY ("NAME" NOT NULL ENABLE);
  ALTER TABLE "JUXXI"."EMP2" MODIFY ("DEPTNO" NOT NULL ENABLE);
  ALTER TABLE "JUXXI"."EMP2" ADD PRIMARY KEY ("EMPNO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table MEMBER
--------------------------------------------------------

  ALTER TABLE "JUXXI"."MEMBER" MODIFY ("NO" NOT NULL ENABLE);
  ALTER TABLE "JUXXI"."MEMBER" MODIFY ("NAME" NOT NULL ENABLE);
  ALTER TABLE "JUXXI"."MEMBER" MODIFY ("PASSWD" NOT NULL ENABLE);
  ALTER TABLE "JUXXI"."MEMBER" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "JUXXI"."MEMBER" ADD PRIMARY KEY ("JUMIN")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "JUXXI"."MEMBER" ADD UNIQUE ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table DEPARTMENT
--------------------------------------------------------

  ALTER TABLE "JUXXI"."DEPARTMENT" MODIFY ("DNAME" NOT NULL ENABLE);
  ALTER TABLE "JUXXI"."DEPARTMENT" ADD PRIMARY KEY ("DEPTNO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table HELLO
--------------------------------------------------------

  ALTER TABLE "JUXXI"."HELLO" ADD PRIMARY KEY ("NUM")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table SALES
--------------------------------------------------------

  ALTER TABLE "JUXXI"."SALES" ADD PRIMARY KEY ("NUM")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table BOARD
--------------------------------------------------------

  ALTER TABLE "JUXXI"."BOARD" ADD CONSTRAINT "BOARD_PK_BNO" PRIMARY KEY ("BNO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table MYSHOP
--------------------------------------------------------

  ALTER TABLE "JUXXI"."MYSHOP" ADD PRIMARY KEY ("NO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table STUDENT
--------------------------------------------------------

  ALTER TABLE "JUXXI"."STUDENT" MODIFY ("NAME" NOT NULL ENABLE);
  ALTER TABLE "JUXXI"."STUDENT" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "JUXXI"."STUDENT" MODIFY ("JUMIN" NOT NULL ENABLE);
  ALTER TABLE "JUXXI"."STUDENT" ADD CHECK (grade between 1 and 6) ENABLE;
  ALTER TABLE "JUXXI"."STUDENT" ADD PRIMARY KEY ("STUDNO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "JUXXI"."STUDENT" ADD UNIQUE ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table ANSWER
--------------------------------------------------------

  ALTER TABLE "JUXXI"."ANSWER" ADD CONSTRAINT "ANSEWR_FK_BNO" FOREIGN KEY ("BNO")
	  REFERENCES "JUXXI"."BOARD" ("BNO") ON DELETE CASCADE ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table CART1
--------------------------------------------------------

  ALTER TABLE "JUXXI"."CART1" ADD CONSTRAINT "CART_FK_NUM" FOREIGN KEY ("NUM")
	  REFERENCES "JUXXI"."SHOP" ("NUM") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table CART2
--------------------------------------------------------

  ALTER TABLE "JUXXI"."CART2" ADD CONSTRAINT "CART2_FK_NUM" FOREIGN KEY ("NUM")
	  REFERENCES "JUXXI"."SHOP" ("NUM") ON DELETE CASCADE ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table EMP
--------------------------------------------------------

  ALTER TABLE "JUXXI"."EMP" ADD CONSTRAINT "FK_DEPTNO" FOREIGN KEY ("DEPTNO")
	  REFERENCES "JUXXI"."DEPT" ("DEPTNO") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table FOODORDER
--------------------------------------------------------

  ALTER TABLE "JUXXI"."FOODORDER" ADD CONSTRAINT "FOODORDER_FK_FNO" FOREIGN KEY ("FNO")
	  REFERENCES "JUXXI"."FOODMENU" ("FNO") ON DELETE CASCADE ENABLE;
