CREATE SEQUENCE seq_food START WITH 1 INCREMENT BY 3 NOCACHE;

-- FOODMENU 테이블 생성
CREATE TABLE FOODMENU (
    FNO NUMBER(7) PRIMARY KEY, 
    FOOD_NAME VARCHAR2(30), 
    PRICE NUMBER(30), 
    SHOP_NAME VARCHAR2(20), 
    LOC VARCHAR2(20)
);

INSERT INTO FOODMENU VALUES (seq_food.NEXTVAL, '알리오올리오', 17000, '호담', '역삼동');
INSERT INTO FOODMENU VALUES (seq_food.NEXTVAL, '까르보나라', 19000, '허쉬', '방배동');
INSERT INTO FOODMENU VALUES (seq_food.NEXTVAL, '필라프', 18000, '엔젤', '역삼동');
INSERT INTO FOODMENU VALUES (seq_food.NEXTVAL, '피자', 22000, '아키', '서초동');
INSERT INTO FOODMENU VALUES (seq_food.NEXTVAL, '스테이크', 37000, '수피아', '논현동');


-- FOODORDER 테이블 생성 (FOODMENU 테이블이 먼저 생성된 후 실행해야 함)
CREATE TABLE FOODORDER (
    NO NUMBER(5) PRIMARY KEY,  
    ORDER_NAME VARCHAR2(20), 
    FNO NUMBER(7),  
    ADDR VARCHAR2(20), 
    CONSTRAINT FOODORDER_FK_FNO FOREIGN KEY (FNO) 
        REFERENCES FOODMENU(FNO) 
        ON DELETE CASCADE
);

INSERT INTO FOODORDER VALUES (seq_food.NEXTVAL, '안정아', 1, '역삼동');
INSERT INTO FOODORDER VALUES (seq_food.NEXTVAL, '하지웅', 4, '논현동'); -- 기존 데이터에 없는 8 → 4로 변경
INSERT INTO FOODORDER VALUES (seq_food.NEXTVAL, '구준희', 2, '방배동'); -- 기존 데이터에 없는 7 → 2로 변경
INSERT INTO FOODORDER VALUES (seq_food.NEXTVAL, '이주연', 3, '역삼동');

SELECT 
    FOODORDER.FNO AS 주문번호, 
    ORDER_NAME AS 주문자, 
    FOOD_NAME AS 음식명, 
    PRICE AS 가격, 
    SHOP_NAME AS 상호명,
    LOC AS 가게위치,
    ADDR AS 주문자주소
FROM FOODMENU
JOIN FOODORDER ON FOODMENU.FNO = FOODORDER.FNO;

-- 전체 테이블 조회
SELECT * FROM FOODORDER;
SELECT * FROM FOODMENU;
