server:
  port: 9002
spring:
  thymeleaf:
    cache: false
#mysql_setting
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/rain?serverTimezone=Asia/Seoul
    username: angel
    password: a1234
#mybatis
mybatis:
  type-aliases-package: thyme.data.dto
  mapper-locations:
  - /mapper/**/*.xml